src/Entity/Gauntlet.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GauntletRepository")
 */
class Gauntlet
{
    const STATUS_CURRENT = 'CURRENT';
    const STATUS_FINISH = 'FINISH';
    const STATUS_CONCEDED = 'CONCEDED';


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     *
     * @Gedmo\Timestampable(on="create")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @Gedmo\Timestampable(on="update")
     */
    private $updated;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="gauntlets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\GauntletType", inversedBy="gauntlets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Deck", inversedBy="gauntlets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $deck;

    /**
     * @ORM\Column(type="integer")
     */
    private $number;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Game", mappedBy="gauntlet", orphanRemoval=true)
     */
    private $games;

    /**
     * @ORM\Column(type="datetime")
     */
    private $playedAt;

    public function __construct()
    {
        $this->status = self::STATUS_CURRENT;
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getUpdated(): ?\DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(?\DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getType(): ?GauntletType
    {
        return $this->type;
    }

    public function setType(?GauntletType $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDeck(): ?Deck
    {
        return $this->deck;
    }

    public function setDeck(?Deck $deck): self
    {
        $this->deck = $deck;

        return $this;
    }

    public function getNumber(): ?int
    {
        return $this->number;
    }

    public function setNumber(int $number): self
    {
        $this->number = $number;

        return $this;
    }

    /**
     * @return Collection|Game[]
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games[] = $game;
            $game->setGauntlet($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->contains($game)) {
            $this->games->removeElement($game);
            // set the owning side to null (unless already changed)
            if ($game->getGauntlet() === $this) {
                $game->setGauntlet(null);
            }
        }

        return $this;
    }

    /**
     * @param bool $includeDraw
     * @return Game[]
     */
    public function getGamesLost($includeDraw = true)
    {
        $games = [];
        foreach ($this->getGames() as $game) {
            if ($game->getStatus() === Game::STATUS_LOSE || ($includeDraw && $game->getStatus() === Game::STATUS_DRAW)) {
                $games[] = $game;
            }
        }

        return $games;
    }

    /**
     * @return Game[]
     */
    public function getGamesWon()
    {
        $games = [];
        foreach ($this->getGames() as $game) {
            if ($game->getStatus() === Game::STATUS_WIN) {
                $games[] = $game;
            }
        }

        return $games;
    }

    /**
     * @return bool
     */
    public function isPossibleToAddGame()
    {
        $addGame = true;
        if (count($this->getGames()) === 7 || count($this->getGamesWon()) === 5 || count($this->getGamesLost()) === 2) {
            $addGame = false;
        }

        return $addGame;
    }

    /**
     * @return bool
     */
    public function isLock()
    {
       return $this->getStatus() !== self::STATUS_CURRENT;
    }

    public function getPlayedAt(): ?\DateTimeInterface
    {
        return $this->playedAt;
    }

    public function setPlayedAt(?\DateTimeInterface $playedAt): self
    {
        $this->playedAt = $playedAt;

        return $this;
    }
}

src/Entity/GauntletType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Translatable\Translatable;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GauntletTypeRepository")
 */
class GauntletType implements Translatable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     *
     * @Gedmo\Translatable
     */
    private $name;

    /**
     * @Gedmo\Locale
     */
    private $locale;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Gauntlet", mappedBy="type", orphanRemoval=true)
     */
    private $gauntlets;

    public function __construct()
    {
        $this->gauntlets = new ArrayCollection();
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return GauntletType
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @param $locale
     * @return GauntletType
     */
    public function setTranslatableLocale($locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    /**
     * @return Collection|Gauntlet[]
     */
    public function getGauntlets(): Collection
    {
        return $this->gauntlets;
    }

    public function addGauntlet(Gauntlet $gauntlet): self
    {
        if (!$this->gauntlets->contains($gauntlet)) {
            $this->gauntlets[] = $gauntlet;
            $gauntlet->setType($this);
        }

        return $this;
    }

    public function removeGauntlet(Gauntlet $gauntlet): self
    {
        if ($this->gauntlets->contains($gauntlet)) {
            $this->gauntlets->removeElement($gauntlet);
            // set the owning side to null (unless already changed)
            if ($gauntlet->getType() === $this) {
                $gauntlet->setType(null);
            }
        }

        return $this;
    }
}

src/Controller/GauntletController.php
<?php

namespace App\Controller;

use App\Entity\Gauntlet;
use App\Exception\GauntletNotNullException;
use App\Form\GauntletType;
use App\Service\DeckService;
use App\Service\GauntletService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Intl\Intl;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

class GauntletController extends AbstractController
{
    /**
     * @param Request $request
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return \Symfony\Component\HttpFoundation\JsonResponse
     *
     * @Route("/gauntlet-list", name="app_gauntlet_list")
     */
    public function list(Request $request, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        $draw = $request->get('draw', 1);
        $length = $request->get('length', 10);
        $start = $request->get('start', 0);
        $order = $request->get('order', [
            "column" => "1",
            "dir" => "desc"
        ]);

        $columnsMapping = [
            '0' => 'number',
            '1' => 'playedAt',
            '2' => 'type',
            '3' => 'status'
        ];

        $orderName = $columnsMapping[$order[0]['column']];
        $orderDir = $order[0]['dir'];

        $dateFormatter = new \IntlDateFormatter($request->getLocale(), \IntlDateFormatter::SHORT, \IntlDateFormatter::SHORT);

        $total = $gauntletService->getTotalGauntlets($this->getUser());
        $gauntlets = $gauntletService->list($this->getUser(), $start, $length, $orderName, $orderDir);

        $result = [
            'draw' => $draw,
            'recordsTotal' => $total,
            'recordsFiltered' => $total,
        ];

        foreach ($gauntlets as $gauntlet) {
            $result['data'][] = [
                'id' => $gauntlet->getId(),
                'number' => $gauntlet->getNumber(),
                'playedAt' => $dateFormatter->format($gauntlet->getPlayedAt()),
                'type' => $gauntlet->getType()->getName(),
                'status' => $gauntlet->getStatus(),
                'actions' => $translator->trans('btn.show'),
                'countGamesWon' => count($gauntlet->getGamesWon()),
                'countGamesLost' => count($gauntlet->getGamesLost()),
            ];
        }

        return new JsonResponse($result);
    }

    /**
     * @Route("/gauntlet-show-history", name="app_gauntlet_show_history")
     */
    public function showHistory()
    {
        return $this->render('gauntlet/show_history.html.twig');
    }

    /**
     * @param Request $request
     * @param DeckService $deckService
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return JsonResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \App\Exception\CardNotFoundException
     * @throws \App\Exception\GauntletNotNullException
     *
     * @Route("/add-gauntlet", name="app_gauntlet_add")
     */
    public function add(Request $request, DeckService $deckService, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        // On check qu'un affrontement "en cours" existe
        $gauntlet = $gauntletService->getCurrent($this->getUser());
        if ($gauntlet !== null) {
            return $this->redirectToRoute('app_gauntlet_show', ['id' => $gauntlet->getId()]);
        }

        // On crée un affrontement
        $gauntlet = new Gauntlet();

        $form = $this->createForm(GauntletType::class, $gauntlet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $deckCode = $form->get('deckCode')->getData();
            $deck = $deckService->createDeckFromCode($deckCode);

            $gauntlet->setDeck($deck)
                ->setUser($this->getUser());

            $gauntletService->create($gauntlet);

            $this->addFlash(
                'success',
                $translator->trans('success.add_gauntlet')
            );

            return new JsonResponse([
                'success' => true,
                'gauntletId' => $gauntlet->getId()
            ]);
        }

        return $this->render('gauntlet/add.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @param Gauntlet $gauntlet
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("/gauntlet/{id}", name="app_gauntlet_show")
     */
    public function show(Gauntlet $gauntlet)
    {
        return $this->render('gauntlet/show.html.twig', [
            'gauntlet' => $gauntlet
        ]);
    }


    /**
     * @param Gauntlet $gauntlet
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return JsonResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Route("/unlock-gauntlet/{id}", name="app_gauntlet_unlock")
     */
    public function unlock(Gauntlet $gauntlet, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        try {
            $gauntletService->unlock($gauntlet);
        } catch (GauntletNotNullException $e) {
            return $this->render('gauntlet/unlock.html.twig');
        }

        $this->addFlash(
            'success',
            $translator->trans('success.unlock_gauntlet')
        );

        return new JsonResponse([
            'success' => true
        ]);
    }

    /**
     * @param Gauntlet $gauntlet
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return JsonResponse
     * @throws \App\Exception\GauntletLockException
     *
     * @Route("/lock-gauntlet/{id}", name="app_gauntlet_lock")
     */
    public function lock(Gauntlet $gauntlet, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        $gauntletService->lock($gauntlet);

        $this->addFlash(
            'success',
            $translator->trans('success.lock_gauntlet')
        );

        return new JsonResponse([
            'success' => true
        ]);
    }

    /**
     * @param Gauntlet $gauntlet
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return JsonResponse
     * @throws \App\Exception\GauntletStatusException
     *
     * @Route("/concede-gauntlet/{id}", name="app_gauntlet_concede")
     */
    public function concede(Gauntlet $gauntlet, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        $gauntletService->concede($gauntlet);

        $this->addFlash(
            'success',
            $translator->trans('success.concede_gauntlet')
        );

        return new JsonResponse([
            'success' => true
        ]);
    }


    /**
     * @param Request $request
     * @param Gauntlet $gauntlet
     * @param DeckService $deckService
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return JsonResponse|\Symfony\Component\HttpFoundation\Response
     * @throws GauntletNotNullException
     * @throws \App\Exception\CardNotFoundException
     * @throws \App\Exception\GauntletStatusException
     *
     * @Route("/edit-gauntlet/{id}", name="app_gauntlet_edit")
     */
    public function edit(Request $request, Gauntlet $gauntlet, DeckService $deckService, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        $form = $this->createForm(GauntletType::class, $gauntlet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $deckCode = $form->get('deckCode')->getData();

            if ($deckCode !== $gauntlet->getDeck()->getCode()) {
                $deck = $deckService->createDeckFromCode($deckCode);
                $gauntletService->changeDeck($gauntlet, $deck);
            }

            $gauntletService->edit($gauntlet);

            $this->addFlash(
                'success',
                $translator->trans('success.edit_gauntlet')
            );

            return new JsonResponse([
                'success' => true
            ]);
        }

        return $this->render('gauntlet/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @param Gauntlet $gauntlet
     * @param GauntletService $gauntletService
     * @param TranslatorInterface $translator
     * @return JsonResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Route("/delete-gauntlet/{id}", name="app_gauntlet_delete")
     */
    public function delete(Request $request, Gauntlet $gauntlet, GauntletService $gauntletService, TranslatorInterface $translator)
    {
        $form = $this->createForm(FormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $gauntletService->delete($gauntlet);

            $this->addFlash(
                'success',
                $translator->trans('success.delete_gauntlet')
            );

            return new JsonResponse([
                'success' => true
            ]);
        }

        return $this->render('gauntlet/delete.html.twig', [
            'form' => $form->createView(),
            'gauntlet' => $gauntlet
        ]);
    }
}

templates/gauntlet/add.html.twig
<div class="modal fade" id="modal-add-gauntlet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ 'title.add_gauntlet'|trans }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form_row(form.type) }}
                {{ form_row(form.deckCode) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'btn.close'|trans }}</button>
                {#<button type="button" class="btn btn-primary">Save changes</button>#}
                {{ form_widget(form.submit) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
</div>

<script type="application/javascript">
    $(document).ready(function() {
        $('form[name="gauntlet"]').submit(addGauntlet)
    })
</script>

templates/gauntlet/delete.html.twig
<div class="modal fade" id="modal-delete-gauntlet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ 'title.delete_gauntlet'|trans }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {{ form_widget(form) }}
                {{ 'question.delete_gauntlet'|trans }} #{{ gauntlet.number }} ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'btn.close'|trans }}</button>
                <button type="submit" class="btn btn-primary">{{ 'btn.submit'|trans }}</button>
            </div>
        </div>
        {{ form_end(form) }}
    </div>
</div>

<script type="application/javascript">
    $(document).ready(function() {
        $('form[name="form"]').submit(deleteGauntlet)
    })
</script>

templates/gauntlet/edit.html.twig
<div class="modal fade" id="modal-edit-gauntlet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ 'title.edit_gauntlet'|trans }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% include 'gauntlet/form.html.twig' %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ 'btn.close'|trans }}</button>
                {{ form_widget(form.submit) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
</div>

<script type="application/javascript">
    $(document).ready(function() {
        $('form[name="gauntlet"]').submit(editGauntlet)
    })
</script>

templates/gauntlet/form.html.twig
{{ form_row(form.type) }}

<div class="form-group">
    {{ form_label(form.deckCode) }}
    <div class="input-group">
        {{ form_widget(form.deckCode) }}
        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-clone"></i>
                            </span>
        </div>
    </div>
</div>

<div class="form-group">
    {{ form_label(form.playedAt) }}
    <div class="input-group">
        {{ form_widget(form.playedAt) }}
        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="fas fa-calendar-alt"></i>
                            </span>
        </div>
    </div>
</div>

{{ form_errors(form) }}

<script type="application/javascript">
    $(document).ready(function () {
        $('input[name="gauntlet[playedAt]"]').datetimepicker({
            locale: '{{ app.request.locale }}',
            format: "YYYY-MM-DD HH:mm"
        });
    })
</script>

templates/gauntlet/show.html.twig
{% extends 'dashboard/index.html.twig' %}

{% block title %}{% endblock %}

{% block dashboard_body %}
    <div class="row card">
        <div class="card-header">
            <h2>
                {{ 'label.gauntlet'|trans }} #{{ gauntlet.number }} | {{ gauntlet.type.name }}

                {{ gauntletStatusBadge(gauntlet.status) }}
                <div class="float-right" role="group">
                    {% if gauntlet.status == constant('App\\Entity\\Gauntlet::STATUS_CURRENT') and gauntlet.possibleToAddGame == true %}
                        <button type="button" class="btn btn-secondary" id="btn-concede-gauntlet">
                            {{ 'btn.concede_gauntlet'|trans }}
                        </button>
                    {% endif %}

                    {% if gauntlet.lock == false %}
                        <button type="button" class="btn btn-secondary" id="btn-edit-gauntlet">
                            <i class="fas fa-edit"></i>
                        </button>
                        <button type="button" class="btn btn-secondary" id="btn-delete-gauntlet">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    {% endif %}

                    {% if gauntlet.lock %}
                        <button type="button" class="btn btn-primary" id="btn-unlock-gauntlet">
                            <i class="fas fa-lock"></i>
                        </button>
                    {% elseif gauntlet.possibleToAddGame == false %}
                        <button type="button" class="btn btn-primary" id="btn-lock-gauntlet">
                            <i class="fas fa-unlock"></i>
                        </button>
                    {% endif %}
                </div>
            </h2>
            <small class="text-center ml-4">{{ 'label.gauntlet_played_at'|trans }} {{ gauntlet.playedAt|localizeddate('short', 'short', app.request.locale) }}</small>
        </div>
        <div class="card-body row">

            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        {{ 'label.your_deck'|trans }} : {{ gauntlet.deck.name }}
                        <a href="{{ gauntlet.deck.code }}" class="float-right" target="_blank"><i
                                    class="fas fa-external-link-alt"></i></a>
                    </div>
                    <div class="card-body">
                        <ul class="list-group">
                            {% for deckCard in gauntlet.deck.deckCards %}
                                <li class="list-group-item">
                                    {{ deckCard.card.name }}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        {{ 'label.your_games'|trans }}
                        {% if gauntlet.lock == false %}
                            <button type="button"
                                    class="btn btn-primary float-right {% if gauntlet.games|length >= 6 %}disabled{% endif %}"
                                    id="btn-add-game">
                                <span class="ladda-label"><i class="fas fa-plus"></i> {{ 'btn.add_game'|trans }}</span>
                            </button>
                        {% endif %}
                    </div>
                    <div class="card-body">

                        <ul class="list-group">
                            {% for game in gauntlet.games %}
                                <li class="list-group-item">
                                    <span>
                                        {{ 'label.game'|trans }} #{{ game.number }}
                                        {% if game.status == constant('App\\Entity\\Game::STATUS_WIN') %}
                                            <span class="badge badge-success">{{ 'label.game_win'|trans }}</span>
                                        {% elseif game.status == constant('App\\Entity\\Game::STATUS_LOSE') %}
                                            <span class="badge badge-danger">{{ 'label.game_lose'|trans }}</span>
                                        {% elseif game.status == constant('App\\Entity\\Game::STATUS_DRAW') %}
                                            <span class="badge badge-secondary">{{ 'label.game_draw'|trans }}</span>
                                        {% endif %}
                                    </span>
                                    <small class="text-center ml-4">{{ 'label.game_played_at'|trans }} {{ game.playedAt|localizeddate('short', 'short', app.request.locale) }}</small>

                                    <div class="btn-group float-right" role="group">
                                        {% if game.opposingDeck is not null %}
                                            <a class=" btn btn-secondary" href="{{ game.opposingDeck.code }}"
                                               target="_blank"><i
                                                        class="fas fa-external-link-alt"></i></a>
                                        {% endif %}
                                        {% if gauntlet.lock == false %}
                                            <button type="button" class="btn btn-secondary btn-edit-game"
                                                    data-game-id="{{ game.id }}">
                                                <i class="fas fa-edit"></i>
                                            </button>
                                            <button type="button" class="btn btn-secondary btn-delete-game"
                                                    data-game-id="{{ game.id }}">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        {% endif %}
                                    </div>


                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="gauntlet" data-gauntlet-id="{{ gauntlet.id }}"></div>
{% endblock %}

{% block dashboard_javascripts %}
    <script type="application/javascript">
        $(document).ready(function () {
            $('#btn-add-game').click(showAddGame)
            $('.btn-edit-game').click(showEditGame)
            $('.btn-delete-game').click(showDeleteGame)
            $('#btn-unlock-gauntlet').click(unlockGauntlet)
            $('#btn-lock-gauntlet').click(lockGauntlet)
            $('#btn-concede-gauntlet').click(concedeGauntlet)
            $('#btn-edit-gauntlet').click(showEditGauntlet)
            $('#btn-delete-gauntlet').click(showDeleteGauntlet)
        })
    </script>
{% endblock %}

templates/gauntlet/unlock.html.twig
<div class="modal fade" id="modal-unlock-gauntlet" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">{{ 'title.unlock_gauntlet'|trans }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger">
                    <p>
                        <i class="fas fa-exclamation-triangle"></i>
                        {{ 'error.unlock_gauntlet'|trans }}
                    </p>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">{{ 'btn.close'|trans }}</button>
            </div>
        </div>
    </div>
</div>